/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.BorderLayout;

/**
 *
 * @author Jhon Nash
 */
public class JFramePrincipal extends javax.swing.JFrame {
    JPanelCreateCandidato pc; 
    JPanelCreateAsesor pa;
    JPanelFuncionAdministrador pf;
    JPanelLoginCandidato jpc;

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
        pc = new JPanelCreateCandidato();
        pa = new JPanelCreateAsesor();
        pf = new JPanelFuncionAdministrador();
        jpc = new JPanelLoginCandidato();
        
    }
    
    //falta hacer

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelUsuarios = new javax.swing.JPanel();
        jbttnAcademico = new javax.swing.JButton();
        jbttnEstudiante = new javax.swing.JButton();
        jbttnAdministrador = new javax.swing.JButton();
        jPanelAyuda = new javax.swing.JPanel();
        jbttnAyuda = new javax.swing.JButton();
        jPanelForm = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelUsuarios.setBackground(new java.awt.Color(64, 141, 42));
        jPanelUsuarios.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuarios"));

        jbttnAcademico.setText("Academico");
        jbttnAcademico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttnAcademicoActionPerformed(evt);
            }
        });

        jbttnEstudiante.setText("Estudiante");
        jbttnEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttnEstudianteActionPerformed(evt);
            }
        });

        jbttnAdministrador.setText("Administrador");
        jbttnAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttnAdministradorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUsuariosLayout = new javax.swing.GroupLayout(jPanelUsuarios);
        jPanelUsuarios.setLayout(jPanelUsuariosLayout);
        jPanelUsuariosLayout.setHorizontalGroup(
            jPanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbttnAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbttnEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbttnAcademico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelUsuariosLayout.setVerticalGroup(
            jPanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuariosLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jbttnAcademico)
                .addGap(46, 46, 46)
                .addComponent(jbttnEstudiante)
                .addGap(40, 40, 40)
                .addComponent(jbttnAdministrador)
                .addContainerGap(367, Short.MAX_VALUE))
        );

        jPanelAyuda.setBackground(new java.awt.Color(64, 141, 42));
        jPanelAyuda.setBorder(javax.swing.BorderFactory.createTitledBorder("Sistema de Apoyo a la Titilacion"));

        jbttnAyuda.setText("Ayuda");
        jbttnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttnAyudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAyudaLayout = new javax.swing.GroupLayout(jPanelAyuda);
        jPanelAyuda.setLayout(jPanelAyudaLayout);
        jPanelAyudaLayout.setHorizontalGroup(
            jPanelAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAyudaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbttnAyuda)
                .addContainerGap())
        );
        jPanelAyudaLayout.setVerticalGroup(
            jPanelAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAyudaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbttnAyuda)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelForm.setPreferredSize(new java.awt.Dimension(430, 580));

        javax.swing.GroupLayout jPanelFormLayout = new javax.swing.GroupLayout(jPanelForm);
        jPanelForm.setLayout(jPanelFormLayout);
        jPanelFormLayout.setHorizontalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanelFormLayout.setVerticalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanelAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelForm, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbttnEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttnEstudianteActionPerformed
        pc.setVisible(true);
        pc.setSize(426,578);
        
               
        jPanelForm.removeAll();
        jPanelForm.add(pc,BorderLayout.CENTER);
        jPanelForm.revalidate();
        jPanelForm.repaint();     
          
    }//GEN-LAST:event_jbttnEstudianteActionPerformed

    private void jbttnAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttnAdministradorActionPerformed
        pf.setVisible(true);
        pf.setSize(381,413);
        
        
        jPanelForm.removeAll();
        jPanelForm.add(pf,BorderLayout.CENTER);
        jPanelForm.revalidate();
        jPanelForm.repaint();
       
    }//GEN-LAST:event_jbttnAdministradorActionPerformed

    private void jbttnAcademicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttnAcademicoActionPerformed
        pa.setVisible(true);
        pa.setSize(400,438);
       
      
        jPanelForm.removeAll();
        jPanelForm.add(pa,BorderLayout.CENTER);
        jPanelForm.revalidate();
        jPanelForm.repaint();
    }//GEN-LAST:event_jbttnAcademicoActionPerformed

    private void jbttnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttnAyudaActionPerformed
        JPanelMostrarLista jpMostrar;
        jpMostrar = new JPanelMostrarLista();
        jpMostrar.setVisible(true);
        jpMostrar.setSize(400,438);

        jPanelForm.removeAll();
        jPanelForm.add(jpMostrar,BorderLayout.CENTER);
        jPanelForm.revalidate();
        jPanelForm.repaint();
    }//GEN-LAST:event_jbttnAyudaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelAyuda;
    private javax.swing.JPanel jPanelForm;
    private javax.swing.JPanel jPanelUsuarios;
    private javax.swing.JButton jbttnAcademico;
    private javax.swing.JButton jbttnAdministrador;
    private javax.swing.JButton jbttnAyuda;
    private javax.swing.JButton jbttnEstudiante;
    // End of variables declaration//GEN-END:variables
}
