/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorGuardaCandidato;
import javax.swing.JOptionPane;

/**
 *
 * @author Jhon Nash
 */
public class JPanelCreateCandidato extends javax.swing.JPanel {
    /**
     * Creates new form JPanelCreateCandidato
     */
    public JPanelCreateCandidato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabNombre = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jLabApPaterno = new javax.swing.JLabel();
        jtxtApellidoPaterno = new javax.swing.JTextField();
        jLabApMaterno = new javax.swing.JLabel();
        jtxtApellidoMaterno = new javax.swing.JTextField();
        jLabCorrElectronico = new javax.swing.JLabel();
        jtxtCorrElectronico = new javax.swing.JTextField();
        jButtonAddFotoCandidato = new javax.swing.JButton();
        jLabMatricula = new javax.swing.JLabel();
        jtxtMatricula = new javax.swing.JTextField();
        jLabGeneracion = new javax.swing.JLabel();
        jtxtGeneracion = new javax.swing.JTextField();
        jLabCarrera = new javax.swing.JLabel();
        jComBoxCarrera = new javax.swing.JComboBox<>();
        jLabNomTesis = new javax.swing.JLabel();
        jtxtNomTesis = new javax.swing.JTextField();
        jLabDircTesis = new javax.swing.JLabel();
        jtxtDircTesis = new javax.swing.JTextField();
        jbttnCartaCompromiso = new javax.swing.JButton();
        jLabTrabajo = new javax.swing.JLabel();
        jRadBtSi = new javax.swing.JRadioButton();
        jRadBtnNo = new javax.swing.JRadioButton();
        jLabLugar1 = new javax.swing.JLabel();
        jtxtEntidad = new javax.swing.JTextField();
        jbttnCartaExposicionMotivos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabHora = new javax.swing.JLabel();
        jbttnHorarioCandidato = new javax.swing.JButton();
        jbttnCancelar = new javax.swing.JButton();
        jbttnGuardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jRdBttnCondicionesSi = new javax.swing.JRadioButton();
        jRdBttnCondicionesNo = new javax.swing.JRadioButton();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jtxtTelefono = new javax.swing.JTextField();
        jlblCreditos = new javax.swing.JLabel();
        jSpinnerCreditos = new javax.swing.JSpinner();
        jtxtAnioMatricula = new javax.swing.JTextField();
        jtxtPlantelMatricula = new javax.swing.JTextField();
        jbttnEditar = new javax.swing.JButton();

        jlabNombre.setText("Nombre ");

        jtxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtNombreKeyTyped(evt);
            }
        });

        jLabApPaterno.setText("Apellido Paterno");

        jtxtApellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtApellidoPaternoKeyTyped(evt);
            }
        });

        jLabApMaterno.setText("Apellido Materno");

        jtxtApellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtApellidoMaternoKeyTyped(evt);
            }
        });

        jLabCorrElectronico.setText("Correo Electronico");

        jtxtCorrElectronico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCorrElectronicoKeyTyped(evt);
            }
        });

        jButtonAddFotoCandidato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/addFoto.png"))); // NOI18N

        jLabMatricula.setText("Matricula");

        jtxtMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtMatriculaKeyTyped(evt);
            }
        });

        jLabGeneracion.setText("Generacion");

        jtxtGeneracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtGeneracionKeyTyped(evt);
            }
        });

        jLabCarrera.setText("Carrera");

        jComBoxCarrera.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabNomTesis.setText("Nombre de Tesis");

        jtxtNomTesis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtNomTesisKeyTyped(evt);
            }
        });

        jLabDircTesis.setText("Director de Tesis");

        jtxtDircTesis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtDircTesisKeyTyped(evt);
            }
        });

        jbttnCartaCompromiso.setText("Carta Compromiso");

        jLabTrabajo.setText("Trabajas?");

        jRadBtSi.setText("Si");
        jRadBtSi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadBtSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadBtSiActionPerformed(evt);
            }
        });

        jRadBtnNo.setSelected(true);
        jRadBtnNo.setText("No");
        jRadBtnNo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadBtnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadBtnNoActionPerformed(evt);
            }
        });

        jLabLugar1.setText("Entidad");

        jtxtEntidad.setEnabled(false);
        jtxtEntidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtEntidadKeyTyped(evt);
            }
        });

        jbttnCartaExposicionMotivos.setText("Carta Exposicion");

        jLabel1.setText("Datos Personales");

        jLabel2.setText("Datos Academicos");

        jLabel3.setText("Datos Laborales");

        jLabHora.setText("Horarios");

        jbttnHorarioCandidato.setText("Crear");
        jbttnHorarioCandidato.setEnabled(false);

        jbttnCancelar.setText("Cancelar");

        jbttnGuardar.setText("Guardar");
        jbttnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttnGuardarActionPerformed(evt);
            }
        });

        jLabel4.setText("Acepto Terminos y condiciones de uso");

        jRdBttnCondicionesSi.setSelected(true);
        jRdBttnCondicionesSi.setText("si");

        jRdBttnCondicionesNo.setText("no");

        jLabel5.setText("Telefono");

        jtxtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtTelefonoKeyTyped(evt);
            }
        });

        jlblCreditos.setText("Creditos");

        jtxtAnioMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtAnioMatriculaKeyTyped(evt);
            }
        });

        jtxtPlantelMatricula.setEditable(false);
        jtxtPlantelMatricula.setText("003");

        jbttnEditar.setText("Editar");
        jbttnEditar.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabNomTesis)
                                    .addComponent(jLabDircTesis)
                                    .addComponent(jLabGeneracion)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabMatricula)
                                        .addGap(64, 64, 64)
                                        .addComponent(jtxtAnioMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxtPlantelMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabCarrera))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbttnCartaCompromiso)
                            .addComponent(jbttnCartaExposicionMotivos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabCorrElectronico)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jtxtCorrElectronico, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                                .addComponent(jtxtTelefono))
                                            .addComponent(jComBoxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtxtNomTesis, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jRadBtnNo)
                                                .addComponent(jtxtDircTesis, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jtxtGeneracion, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtxtMatricula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabApMaterno)
                                            .addComponent(jLabApPaterno)
                                            .addComponent(jlabNombre))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtxtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtxtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                        .addComponent(jButtonAddFotoCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(jlblCreditos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSpinnerCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jbttnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabLugar1)
                                                    .addComponent(jLabHora, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabTrabajo))
                                                .addGap(53, 53, 53)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jtxtEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jRadBtSi)
                                                    .addComponent(jbttnHorarioCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbttnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRdBttnCondicionesSi)
                                        .addGap(51, 51, 51)
                                        .addComponent(jRdBttnCondicionesNo))
                                    .addComponent(jbttnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(26, 26, 26))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabNombre)
                            .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabApPaterno)
                            .addComponent(jtxtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabApMaterno)
                            .addComponent(jtxtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabCorrElectronico)
                            .addComponent(jtxtCorrElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonAddFotoCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabMatricula)
                            .addComponent(jtxtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtAnioMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtPlantelMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtGeneracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabGeneracion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComBoxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabCarrera))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtNomTesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabNomTesis))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtDircTesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabDircTesis)
                            .addComponent(jlblCreditos)
                            .addComponent(jSpinnerCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbttnCartaCompromiso, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbttnCartaExposicionMotivos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadBtSi)
                            .addComponent(jRadBtnNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabLugar1)
                            .addComponent(jtxtEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbttnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabHora, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbttnHorarioCandidato))
                .addGap(12, 12, 12)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRdBttnCondicionesSi)
                    .addComponent(jRdBttnCondicionesNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbttnCancelar)
                    .addComponent(jbttnGuardar))
                .addGap(22, 22, 22))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(191, Short.MAX_VALUE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(385, 385, 385)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadBtSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadBtSiActionPerformed
        /*this.jtxtEntidad.setEditable(true);
        this.jComBoxHora.setEnabled(true);
        this.jRadBtnNo.setSelected(false);
        */
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadBtSiActionPerformed

    private void jRadBtnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadBtnNoActionPerformed
        // TODO add your handling code here:
        /* this.jtxtEntidad.setEditable(false);
        this.jComBoxHora.setEnabled(false);
        this.jRadBtSi.setSelected(false);
        */
    }//GEN-LAST:event_jRadBtnNoActionPerformed

    private void jbttnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttnGuardarActionPerformed
        // TODO add your handling code here:
        ControladorGuardaCandidato cntrldrGurdCandidato;
        if(jtxtNombre.getText().isEmpty()|| jtxtApellidoPaterno.getText().isEmpty()||
                this.jtxtApellidoMaterno.getText().isEmpty()|| 
                this.jtxtCorrElectronico.getText().isEmpty()|| 
                this.jtxtTelefono.getText().isEmpty()|| 
                this.jtxtAnioMatricula.getText().isEmpty()||
                this.jtxtMatricula.getText().isEmpty()|| 
                this.jtxtGeneracion.getText().isEmpty()||
                this.jtxtNomTesis.getText().isEmpty()|| 
                this.jtxtDircTesis.getText().isEmpty()){
            JOptionPane.showMessageDialog(jlblCreditos, "No deje campos vacios ");   
        }else{
            cntrldrGurdCandidato = new ControladorGuardaCandidato(this);
            this.setVisible(false);
        }
        
        
        
        
        
    }//GEN-LAST:event_jbttnGuardarActionPerformed

    private void jtxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNombreKeyTyped
        // TODO add your handling code here:
        int maximoCadena=20;
        if(jtxtNombre.getText().length() >=maximoCadena){
            evt.consume();
            JOptionPane.showMessageDialog(jlabNombre, "Solo 20 caracteres aceptados ");   
        } 
    }//GEN-LAST:event_jtxtNombreKeyTyped

    private void jtxtApellidoPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtApellidoPaternoKeyTyped
        // TODO add your handling code here:
        int maximoCadena=20;
        if(jtxtApellidoPaterno.getText().length() >=maximoCadena){
            evt.consume();
            JOptionPane.showMessageDialog(jlabNombre, "Solo 20 caracteres aceptados ");   
        }
    }//GEN-LAST:event_jtxtApellidoPaternoKeyTyped

    private void jtxtApellidoMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtApellidoMaternoKeyTyped
        // TODO add your handling code here:
        int maximoCadena=20;
        if(jtxtApellidoMaterno.getText().length() >=maximoCadena){
            evt.consume();
            JOptionPane.showMessageDialog(jlabNombre, "Solo 20 caracteres aceptados ");   
        }
    }//GEN-LAST:event_jtxtApellidoMaternoKeyTyped

    private void jtxtCorrElectronicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCorrElectronicoKeyTyped
        // TODO add your handling code here:
        int maximoCadena=30;
        if(jtxtCorrElectronico.getText().length() >=maximoCadena){
            evt.consume();
            JOptionPane.showMessageDialog(jlabNombre, "Solo 30 caracteres aceptados ");   
        }
    }//GEN-LAST:event_jtxtCorrElectronicoKeyTyped

    private void jtxtAnioMatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtAnioMatriculaKeyTyped
        // TODO add your handling code here:
        int maximoCadena=2;
        if(jtxtAnioMatricula.getText().length() >=maximoCadena){
            evt.consume();
            JOptionPane.showMessageDialog(jlabNombre, "Solo 2 digitos aceptados ");   
        }
    }//GEN-LAST:event_jtxtAnioMatriculaKeyTyped

    private void jtxtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTelefonoKeyTyped
        // TODO add your handling code here:
        int maximoCadena=15;
        if(jtxtTelefono.getText().length() >=maximoCadena){
            evt.consume();
            JOptionPane.showMessageDialog(jlabNombre, "Solo 15 digitos aceptados ");   
        }
    }//GEN-LAST:event_jtxtTelefonoKeyTyped

    private void jtxtMatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtMatriculaKeyTyped
        // TODO add your handling code here:
        int maximoCadena=4;
        if(jtxtMatricula.getText().length() >=maximoCadena){
            evt.consume();
            JOptionPane.showMessageDialog(jlabNombre, "Solo 4 digitos aceptados ");   
        }
        
    }//GEN-LAST:event_jtxtMatriculaKeyTyped

    private void jtxtGeneracionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtGeneracionKeyTyped
        // TODO add your handling code here:
        int maximoCadena=4;
        if(jtxtGeneracion.getText().length() >=maximoCadena){
            evt.consume();
            JOptionPane.showMessageDialog(jlabNombre, "Solo 4 digitos aceptados");   
        }
    }//GEN-LAST:event_jtxtGeneracionKeyTyped

    private void jtxtNomTesisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNomTesisKeyTyped
        // TODO add your handling code here:
        int maximoCadena=40;
        if(jtxtNomTesis.getText().length() >=maximoCadena){
            evt.consume();
            JOptionPane.showMessageDialog(jlabNombre, "Solo 40 caracteres aceptados ");   
        }
    }//GEN-LAST:event_jtxtNomTesisKeyTyped

    private void jtxtDircTesisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDircTesisKeyTyped
        // TODO add your handling code here:
        int maximoCadena=40;
        if(jtxtDircTesis.getText().length() >=maximoCadena){
            evt.consume();
            JOptionPane.showMessageDialog(jlabNombre, "Solo 40 caracteres aceptados ");   
        }
    }//GEN-LAST:event_jtxtDircTesisKeyTyped

    private void jtxtEntidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtEntidadKeyTyped
        // TODO add your handling code here:
        int maximoCadena=40;
        if(jtxtEntidad.getText().length() >=maximoCadena){
            evt.consume();
            JOptionPane.showMessageDialog(jlabNombre, "Solo 40 caracteres aceptados ");   
        }
    }//GEN-LAST:event_jtxtEntidadKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton jButtonAddFotoCandidato;
    public javax.swing.JComboBox<String> jComBoxCarrera;
    private javax.swing.JLabel jLabApMaterno;
    private javax.swing.JLabel jLabApPaterno;
    private javax.swing.JLabel jLabCarrera;
    private javax.swing.JLabel jLabCorrElectronico;
    private javax.swing.JLabel jLabDircTesis;
    private javax.swing.JLabel jLabGeneracion;
    private javax.swing.JLabel jLabHora;
    private javax.swing.JLabel jLabLugar1;
    private javax.swing.JLabel jLabMatricula;
    private javax.swing.JLabel jLabNomTesis;
    private javax.swing.JLabel jLabTrabajo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JRadioButton jRadBtSi;
    public javax.swing.JRadioButton jRadBtnNo;
    public javax.swing.JRadioButton jRdBttnCondicionesNo;
    public javax.swing.JRadioButton jRdBttnCondicionesSi;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    public javax.swing.JSpinner jSpinnerCreditos;
    public javax.swing.JButton jbttnCancelar;
    public javax.swing.JButton jbttnCartaCompromiso;
    public javax.swing.JButton jbttnCartaExposicionMotivos;
    private javax.swing.JButton jbttnEditar;
    public javax.swing.JButton jbttnGuardar;
    public javax.swing.JButton jbttnHorarioCandidato;
    private javax.swing.JLabel jlabNombre;
    private javax.swing.JLabel jlblCreditos;
    public javax.swing.JTextField jtxtAnioMatricula;
    public javax.swing.JTextField jtxtApellidoMaterno;
    public javax.swing.JTextField jtxtApellidoPaterno;
    public javax.swing.JTextField jtxtCorrElectronico;
    public javax.swing.JTextField jtxtDircTesis;
    public javax.swing.JTextField jtxtEntidad;
    public javax.swing.JTextField jtxtGeneracion;
    public javax.swing.JTextField jtxtMatricula;
    public javax.swing.JTextField jtxtNomTesis;
    public javax.swing.JTextField jtxtNombre;
    public javax.swing.JTextField jtxtPlantelMatricula;
    public javax.swing.JTextField jtxtTelefono;
    // End of variables declaration//GEN-END:variables
}
