/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Jhon Nash
 */
public class JPanelFuncionAdministrador extends javax.swing.JPanel {

    /**
     * Creates new form JPanelFuncionAdministrador
     */
    public JPanelFuncionAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jbttnIniciaRegistro = new javax.swing.JButton();
        jbttnFinalizaRegistro = new javax.swing.JButton();
        jbttnAceptaCandidatos = new javax.swing.JButton();
        jbttnAsignaPrivilegios = new javax.swing.JButton();
        jbttnAsignarAsesorGrupo = new javax.swing.JButton();
        jbttnSalir = new javax.swing.JButton();
        jbttnAgregaCandidato = new javax.swing.JButton();
        jbttnAgregaAsesor = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        jSeparator1.setBorder(javax.swing.BorderFactory.createTitledBorder("Funciones de Administrador"));

        jbttnIniciaRegistro.setText("Inicia Registro a Seminario");

        jbttnFinalizaRegistro.setText("Finaliza Registro a Seminario");
        jbttnFinalizaRegistro.setEnabled(false);

        jbttnAceptaCandidatos.setText("Acepta Candidatos");
        jbttnAceptaCandidatos.setEnabled(false);

        jbttnAsignaPrivilegios.setText("Asignar Privilegios");
        jbttnAsignaPrivilegios.setEnabled(false);

        jbttnAsignarAsesorGrupo.setText("Asignar Asesores y Grupos");
        jbttnAsignarAsesorGrupo.setEnabled(false);

        jbttnSalir.setText("Salir");

        jbttnAgregaCandidato.setText("Registra Candidato");
        jbttnAgregaCandidato.setEnabled(false);

        jbttnAgregaAsesor.setText("Registra Asesor");
        jbttnAgregaAsesor.setEnabled(false);

        jSeparator2.setBorder(javax.swing.BorderFactory.createTitledBorder("Etapa de Registro"));

        jSeparator3.setBorder(javax.swing.BorderFactory.createTitledBorder("Etapa Asignaciones de Asesor y Grupo"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(308, 308, 308)
                                    .addComponent(jbttnSalir))
                                .addComponent(jbttnAsignaPrivilegios, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbttnAceptaCandidatos, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbttnIniciaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jbttnAgregaCandidato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbttnFinalizaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbttnAgregaAsesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jbttnAsignarAsesorGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbttnIniciaRegistro)
                .addGap(13, 13, 13)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbttnAgregaCandidato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbttnAgregaAsesor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbttnFinalizaRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbttnAceptaCandidatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbttnAsignaPrivilegios)
                .addGap(13, 13, 13)
                .addComponent(jbttnAsignarAsesorGrupo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jbttnSalir)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbttnAceptaCandidatos;
    private javax.swing.JButton jbttnAgregaAsesor;
    private javax.swing.JButton jbttnAgregaCandidato;
    private javax.swing.JButton jbttnAsignaPrivilegios;
    private javax.swing.JButton jbttnAsignarAsesorGrupo;
    private javax.swing.JButton jbttnFinalizaRegistro;
    public javax.swing.JButton jbttnIniciaRegistro;
    private javax.swing.JButton jbttnSalir;
    // End of variables declaration//GEN-END:variables
}
