/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Jhon Nash
 */
public class JPanelRegistroCandidato extends javax.swing.JPanel {

    /**
     * Creates new form JPanelRegistroCandidato
     */
    public JPanelRegistroCandidato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDatosPersonales = new javax.swing.JPanel();
        jlabNombre = new javax.swing.JLabel();
        jLabApPaterno = new javax.swing.JLabel();
        jLabApMaterno = new javax.swing.JLabel();
        jLabCorrElectronico = new javax.swing.JLabel();
        jLabTelCelular = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jtxtApellidoPaterno = new javax.swing.JTextField();
        jtxtApellidoMaterno = new javax.swing.JTextField();
        jtxtCorrElectronico = new javax.swing.JTextField();
        jtxtNumTelefono = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabMatricula = new javax.swing.JLabel();
        jLabCarrera = new javax.swing.JLabel();
        jLabGeneracion = new javax.swing.JLabel();
        jLabNomTesis = new javax.swing.JLabel();
        jLabDircTesis = new javax.swing.JLabel();
        jtxtMatricula = new javax.swing.JTextField();
        jtxtGeneracion = new javax.swing.JTextField();
        jComBoxCarrera = new javax.swing.JComboBox<>();
        jtxtNomTesis = new javax.swing.JTextField();
        jtxtDircTesis = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabTrabajo = new javax.swing.JLabel();
        jRadBtSi = new javax.swing.JRadioButton();
        jRadBtnNo = new javax.swing.JRadioButton();
        jLabLugar1 = new javax.swing.JLabel();
        jtxtEntidad = new javax.swing.JTextField();
        jLabHora = new javax.swing.JLabel();
        jbttnHorarioCandidato = new javax.swing.JButton();
        jLabLugar = new javax.swing.JLabel();
        jPanelFotoCandidato = new javax.swing.JPanel();
        jButtonAddFotoCandidato = new javax.swing.JButton();
        jPanelDocumentacion = new javax.swing.JPanel();
        jbttnCartaCompromiso = new javax.swing.JButton();
        jbttnCartaExposicionMotivos = new javax.swing.JButton();
        jPanelCondicionesUso = new javax.swing.JPanel();
        jRdBttnCondicionesSi = new javax.swing.JRadioButton();
        jRdBttnCondicionesNo = new javax.swing.JRadioButton();
        jbttnCancelar = new javax.swing.JButton();
        jbttnGuardar = new javax.swing.JButton();

        setLayout(null);

        jPanelDatosPersonales.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));
        jPanelDatosPersonales.setFont(new java.awt.Font("Segoe UI Symbol", 1, 11)); // NOI18N

        jlabNombre.setText("Nombre de Candidato");

        jLabApPaterno.setText("Apellido Paterno");

        jLabApMaterno.setText("Apellido Materno");

        jLabCorrElectronico.setText("Correo Electronico");

        jLabTelCelular.setText("Telefono Celular");

        jtxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosPersonalesLayout = new javax.swing.GroupLayout(jPanelDatosPersonales);
        jPanelDatosPersonales.setLayout(jPanelDatosPersonalesLayout);
        jPanelDatosPersonalesLayout.setHorizontalGroup(
            jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabNombre)
                            .addComponent(jLabApPaterno)
                            .addComponent(jLabApMaterno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabCorrElectronico)
                            .addComponent(jLabTelCelular))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtNumTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCorrElectronico))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelDatosPersonalesLayout.setVerticalGroup(
            jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabNombre)
                    .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabApPaterno)
                    .addComponent(jtxtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabApMaterno)
                    .addComponent(jtxtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabCorrElectronico)
                    .addComponent(jtxtCorrElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabTelCelular)
                    .addComponent(jtxtNumTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        add(jPanelDatosPersonales);
        jPanelDatosPersonales.setBounds(0, 0, 250, 170);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Academicos"));

        jLabMatricula.setText("Matricula");

        jLabCarrera.setText("Carrera");

        jLabGeneracion.setText("Generacion");

        jLabNomTesis.setText("Nombre de Tesis");

        jLabDircTesis.setText("Director de Tesis");

        jComBoxCarrera.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComBoxCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComBoxCarreraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabMatricula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabGeneracion)
                            .addComponent(jLabCarrera)
                            .addComponent(jLabNomTesis)
                            .addComponent(jLabDircTesis))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtDircTesis, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComBoxCarrera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtGeneracion)
                                .addComponent(jtxtNomTesis, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabMatricula)
                    .addComponent(jtxtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabGeneracion)
                    .addComponent(jtxtGeneracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComBoxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabCarrera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtNomTesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabNomTesis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabDircTesis)
                    .addComponent(jtxtDircTesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        add(jPanel1);
        jPanel1.setBounds(0, 170, 250, 190);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Laborales"));

        jLabTrabajo.setText("Trabajas?");

        jRadBtSi.setText("Si");
        jRadBtSi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadBtSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadBtSiActionPerformed(evt);
            }
        });

        jRadBtnNo.setText("No");
        jRadBtnNo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadBtnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadBtnNoActionPerformed(evt);
            }
        });

        jLabLugar1.setText("Entidad");

        jLabHora.setText("Horarios");

        jbttnHorarioCandidato.setText("Crear");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabTrabajo)
                    .addComponent(jLabLugar1)
                    .addComponent(jLabHora))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadBtSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadBtnNo))
                    .addComponent(jtxtEntidad)
                    .addComponent(jbttnHorarioCandidato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabTrabajo)
                    .addComponent(jRadBtSi)
                    .addComponent(jRadBtnNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabLugar1)
                    .addComponent(jtxtEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabHora)
                    .addComponent(jbttnHorarioCandidato))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        add(jPanel2);
        jPanel2.setBounds(0, 360, 250, 130);

        jLabLugar.setText("Lugar");
        add(jLabLugar);
        jLabLugar.setBounds(0, 0, 27, 14);

        jPanelFotoCandidato.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto"));

        jButtonAddFotoCandidato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/addFoto.png"))); // NOI18N

        javax.swing.GroupLayout jPanelFotoCandidatoLayout = new javax.swing.GroupLayout(jPanelFotoCandidato);
        jPanelFotoCandidato.setLayout(jPanelFotoCandidatoLayout);
        jPanelFotoCandidatoLayout.setHorizontalGroup(
            jPanelFotoCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonAddFotoCandidato, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );
        jPanelFotoCandidatoLayout.setVerticalGroup(
            jPanelFotoCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonAddFotoCandidato, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
        );

        add(jPanelFotoCandidato);
        jPanelFotoCandidato.setBounds(300, 0, 170, 170);

        jPanelDocumentacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Documentacion"));

        jbttnCartaCompromiso.setText("Carta Compromiso");

        jbttnCartaExposicionMotivos.setText("Carta Exposicion");

        javax.swing.GroupLayout jPanelDocumentacionLayout = new javax.swing.GroupLayout(jPanelDocumentacion);
        jPanelDocumentacion.setLayout(jPanelDocumentacionLayout);
        jPanelDocumentacionLayout.setHorizontalGroup(
            jPanelDocumentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocumentacionLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanelDocumentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbttnCartaExposicionMotivos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbttnCartaCompromiso))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanelDocumentacionLayout.setVerticalGroup(
            jPanelDocumentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocumentacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbttnCartaCompromiso, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbttnCartaExposicionMotivos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        add(jPanelDocumentacion);
        jPanelDocumentacion.setBounds(260, 180, 210, 180);

        jPanelCondicionesUso.setBorder(javax.swing.BorderFactory.createTitledBorder("Acetpto terminos y condiciones de uso"));

        jRdBttnCondicionesSi.setText("si");

        jRdBttnCondicionesNo.setText("no");

        javax.swing.GroupLayout jPanelCondicionesUsoLayout = new javax.swing.GroupLayout(jPanelCondicionesUso);
        jPanelCondicionesUso.setLayout(jPanelCondicionesUsoLayout);
        jPanelCondicionesUsoLayout.setHorizontalGroup(
            jPanelCondicionesUsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCondicionesUsoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jRdBttnCondicionesSi)
                .addGap(40, 40, 40)
                .addComponent(jRdBttnCondicionesNo)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanelCondicionesUsoLayout.setVerticalGroup(
            jPanelCondicionesUsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCondicionesUsoLayout.createSequentialGroup()
                .addGroup(jPanelCondicionesUsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRdBttnCondicionesSi)
                    .addComponent(jRdBttnCondicionesNo))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        add(jPanelCondicionesUso);
        jPanelCondicionesUso.setBounds(260, 370, 210, 50);

        jbttnCancelar.setText("Cancelar");
        add(jbttnCancelar);
        jbttnCancelar.setBounds(270, 450, 80, 23);

        jbttnGuardar.setText("Guardar");
        add(jbttnGuardar);
        jbttnGuardar.setBounds(390, 450, 71, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreActionPerformed

    private void jComBoxCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComBoxCarreraActionPerformed

    }//GEN-LAST:event_jComBoxCarreraActionPerformed

    private void jRadBtSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadBtSiActionPerformed
        /*this.jtxtEntidad.setEditable(true);
        this.jComBoxHora.setEnabled(true);
        this.jRadBtnNo.setSelected(false);
*/
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadBtSiActionPerformed

    private void jRadBtnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadBtnNoActionPerformed
        // TODO add your handling code here:
       /* this.jtxtEntidad.setEditable(false);
        this.jComBoxHora.setEnabled(false);
        this.jRadBtSi.setSelected(false);
*/
    }//GEN-LAST:event_jRadBtnNoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddFotoCandidato;
    private javax.swing.JComboBox<String> jComBoxCarrera;
    private javax.swing.JLabel jLabApMaterno;
    private javax.swing.JLabel jLabApPaterno;
    private javax.swing.JLabel jLabCarrera;
    private javax.swing.JLabel jLabCorrElectronico;
    private javax.swing.JLabel jLabDircTesis;
    private javax.swing.JLabel jLabGeneracion;
    private javax.swing.JLabel jLabHora;
    private javax.swing.JLabel jLabLugar;
    private javax.swing.JLabel jLabLugar1;
    private javax.swing.JLabel jLabMatricula;
    private javax.swing.JLabel jLabNomTesis;
    private javax.swing.JLabel jLabTelCelular;
    private javax.swing.JLabel jLabTrabajo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCondicionesUso;
    private javax.swing.JPanel jPanelDatosPersonales;
    private javax.swing.JPanel jPanelDocumentacion;
    private javax.swing.JPanel jPanelFotoCandidato;
    private javax.swing.JRadioButton jRadBtSi;
    private javax.swing.JRadioButton jRadBtnNo;
    private javax.swing.JRadioButton jRdBttnCondicionesNo;
    private javax.swing.JRadioButton jRdBttnCondicionesSi;
    private javax.swing.JButton jbttnCancelar;
    private javax.swing.JButton jbttnCartaCompromiso;
    private javax.swing.JButton jbttnCartaExposicionMotivos;
    private javax.swing.JButton jbttnGuardar;
    private javax.swing.JButton jbttnHorarioCandidato;
    private javax.swing.JLabel jlabNombre;
    private javax.swing.JTextField jtxtApellidoMaterno;
    private javax.swing.JTextField jtxtApellidoPaterno;
    private javax.swing.JTextField jtxtCorrElectronico;
    private javax.swing.JTextField jtxtDircTesis;
    private javax.swing.JTextField jtxtEntidad;
    private javax.swing.JTextField jtxtGeneracion;
    private javax.swing.JTextField jtxtMatricula;
    private javax.swing.JTextField jtxtNomTesis;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtNumTelefono;
    // End of variables declaration//GEN-END:variables
}
